Misc.Fixes 2
StructuralEquationModels/StructuralEquationModels.jl pull request #198
Opened 2024-04-20 23:33 UTC by alyst

Second round of cherry-picking from #193.

This time there are:
* some linear algebra tweaks in ML
* indexing optimizations, esp. in FABIN3. Some helper functions are not actually used in the current code, so maybe they just could be removed.
* some test enhancements: essentially instead of doing `AeqB = A == B; @test AeqB` we do `@test A == B` directly, which provides better diagnostic when the test fails

These commits do not affect the API (except that `n_man` and `n_obs` are now restricted to `Int` -- in all of their usages they were converted back to Int from Float64).

2024-04-21 13:34 UTC, Maximilian-Stefan-Ernst commented on src/additional_functions/helper.jl
> +function neumann_series(mat::SparseMatrixCSC; maxn::Integer = size(mat, 1))
Nice change - it is a fact that if the Neumann series converges in a finite number of steps, it has to be less than `size(mat, 1)`, right?

2024-04-21 13:38 UTC, Maximilian-Stefan-Ernst commented on src/additional_functions/helper.jl
> +function neumann_series(mat::SparseMatrixCSC; maxn::Integer = size(mat, 1))
```suggestion
function neumann_series(mat::SparseMatrixCSC; maxiter::Integer = size(mat, 1))
```

2024-04-21 13:39 UTC, Maximilian-Stefan-Ernst commented on src/additional_functions/helper.jl
> +        (n <= maxn) || error("Neumann series did not converge in $maxn steps")
```suggestion
        (n <= maxiter) || error("Neumann series did not converge in $maxn steps")
```

2024-04-21 13:49 UTC, Maximilian-Stefan-Ernst commented on src/additional_functions/helper.jl
>  end
If you want we could even do
```suggestion
skipmissing_mean(mat::AbstractMatrix) = 
    [mean(skipmissing(coldata)) for coldata in eachcol(mat)]
```

2024-04-21 17:24 UTC, alyst commented on src/additional_functions/helper.jl
> +function neumann_series(mat::SparseMatrixCSC; maxn::Integer = size(mat, 1))
My intuition is that if the matrix has lower triangular form, it should have zeroes on the main diagonal (to converge in finite steps).
Then at each multiplication non-zeroes should move away from the main diagonal, and disappear in at most `size(mat, 1)` steps.

2024-04-21 17:26 UTC, alyst commented on src/additional_functions/helper.jl
> +        (n <= maxn) || error("Neumann series did not converge in $maxn steps")
```suggestion
        (n <= maxiter) || error("Neumann series did not converge in $maxiter steps")
```

2024-04-21 18:14 UTC, Maximilian-Stefan-Ernst commented on src/additional_functions/helper.jl
> +function neumann_series(mat::SparseMatrixCSC; maxn::Integer = size(mat, 1))
Nice. A fun fact I remembered: since the `A` matrix contains the directed effects, the number of iterations of the Neumann series corresponds to the length of the longest directed path in the model 😄 So if your model contains directed loops (is not a DAG), the series won't converge in finite steps.

2024-04-21 18:47 UTC, Maximilian-Stefan-Ernst commented on src/additional_functions/parameters.jl
> +            end
Very nice change. It seems like this is a function that is used nowhere...

2024-04-21 18:56 UTC, alyst commented on src/additional_functions/parameters.jl
> +            end
Yes, there are quite a few helper functions that don't seem to be utilized atm (coverage provides good uptodate overview). I think once most of the proposed changes land, it would be easier to figure out what to do with it (e.g. if they could be used in any future).

2024-04-22 07:56 UTC, Maximilian-Stefan-Ernst commented on src/observed/covariance.jl
> +struct SemObservedCovariance{B, C} <: SemObserved
I'm wondering what best practices is here - I think the old version should not have downsides in terms of performance; restricting the types of these two fields is maybe best done with:
```suggestion
struct SemObservedCovariance{B, C, D <: Int, O <: Int} <: SemObserved
```
I'm not sure when/if annotating the types of specific fields vs. having a parametric type is preferred, maybe you have some thoughts on that?

2024-04-22 08:03 UTC, Maximilian-Stefan-Ernst commented on test/unit_tests/multithreading.jl
> +        @test Threads.nthreads() >= 8
Is there a specific reason for this? This test should be only run on CI, where I set the number of threads to 8.

2024-04-22 08:29 UTC, alyst commented on src/observed/covariance.jl
> +struct SemObservedCovariance{B, C} <: SemObserved
As far as I know, type parameters add some stress on Julia compiler, so if they could be avoided (i.e. if the type is fixed), they should be avoided.
Plus, it makes the code less readable.
In this particular case, it is quite reasonable to fix the number of observations and the number of variables to `Int`.
I don't see usecases, where anything else would be required.

2024-04-22 08:32 UTC, alyst commented on test/unit_tests/multithreading.jl
> +        @test Threads.nthreads() >= 8
Mmm, maybe this logic has changed recently, I have thought before it was always testing the number of threads.
Anyway, if the particular testing configuration (i.e. in the forked repository) has more threads available, I don't see why it should fail.

2024-04-22 08:35 UTC, alyst commented on src/observed/covariance.jl
> +struct SemObservedCovariance{B, C} <: SemObserved
Also, `D <: Int` is, sort of, no-op as `Int` is a concrete type, i.e. it just tells that `D === Int`.
`D <: Integer` allows flexibility, since `Integer` is an abstract type, but, as I wrote in the previous comment, I don't see the benefit of this flexibility here.

2024-04-22 08:53 UTC, Maximilian-Stefan-Ernst commented on src/additional_functions/start_val/start_fabin3.jl
> +    function calculate_lambda(
Is there a reason to have this function definition inside the other function?

2024-04-22 08:59 UTC, alyst commented on src/observed/covariance.jl
> +struct SemObservedCovariance{B, C} <: SemObserved
BTW, here's the [performance tips about type declarations](https://docs.julialang.org/en/v1/manual/performance-tips/#Type-declarations) from Julia manual

2024-04-22 09:05 UTC, alyst commented on src/additional_functions/start_val/start_fabin3.jl
> +    function calculate_lambda(
It could be moved outside (just Σ has to be added as another input parameter), but it is only used from start_fabin3 so far, and to me it looked like both its purpose and reference/indicator terminology are FABIN3-specifc.

2024-04-22 09:33 UTC, Maximilian-Stefan-Ernst commented on src/observed/covariance.jl
> +struct SemObservedCovariance{B, C} <: SemObserved
I see, then let's do it like you suggested. In the manual it only says if you have abstract field types it's better to use parametric Types; but here the field types are concrete (so I guess that makes it okay).

2024-04-22 09:43 UTC, Maximilian-Stefan-Ernst commented on src/additional_functions/start_val/start_fabin3.jl
> +                ref = reference[1]
```suggestion
        if length(reference) > 0
            ref = reference[1]
            if (length(reference) > 1) & isempty(indicator2parampos) # don't warn if entire column is fixed
                    @warn "You have more than 1 scaling indicator for $(ram_matrices.colnames[i])"
            end
```

2024-04-22 09:44 UTC, Maximilian-Stefan-Ernst commented on src/additional_functions/start_val/start_fabin3.jl
> +                ref = reference[1]
Sorry, GitHub does not let me make this suggestion sensible, but I wanted to also delete the following `else` case.

2024-04-22 10:03 UTC, Maximilian-Stefan-Ernst commented on src/imply/RAM/generic.jl
> +    end
Interesting that this is actually faster (and by quite a lot). Maybe we should put it into a function `identity_difference!(I_A, A)` or something like that, because it's used 2 times and you typically don't want to care about it when reading the code. It could live in the `helper.jl` file.

2024-04-22 10:26 UTC, alyst commented on src/imply/RAM/generic.jl
> +    end
Actually, this one is simpler and might be faster:
```suggestion
    axpby!(-1, imply.A, 0, imply.I_A)
    @inbounds imply.I_A[diagind(imply.I_A)] .+= 1
```
It is also quite explicit to deserve a function.

For a function, I'd generalize it to expressions like `C := a I + b B + c C` or at least `C := a I + b B`

2024-04-22 12:31 UTC, Maximilian-Stefan-Ernst commented on src/imply/RAM/generic.jl
> +    end
Benchmarkingit, `axpby!` is a bit slower, but this one is faster:
```suggestion
    @. I_A = -A
    @view(I_A[diagind(I_A)]) .+= 1
```
and also easy enough that it does not need a function.

2024-04-22 12:35 UTC, Maximilian-Stefan-Ernst requested changes
Very nice PR with many improvements. There's only one open comment I think and then we can merge.

2024-04-22 16:32 UTC, alyst commented
Thanks again for very fast review!
I've updated I-A calculation, integrated the review changes into original commits and rebased the PR.

The next round of changes may substantially change some internal structs like RAMMatrices. So potentially you can release the current fixes as the new patch version.

2024-04-22 17:52 UTC, Maximilian-Stefan-Ernst approved these changes

2024-04-22 17:52 UTC, merged

2024-04-22 17:53 UTC, Maximilian-Stefan-Ernst commented
Ah thanks for re-fixing the I-A computation^^
I will release this as a patch.