Refactor SEM Specification
StructuralEquationModels/StructuralEquationModels.jl pull request #203
Opened 2024-05-03 15:18 UTC by alyst

This is a part of #193 that mostly refactors the code for SEM specification types (`RAMMatrices`, `ParameterTable`, `StenoGraph` and `EnsembleParameterTable`):
  * introduces an abstract `SemSpecification` type, which is a parent to all the classes that specify SEM
  * make SEM constructors use Julia type dispatch (which constructor gets called depend on the type of the positional arguments; keyword arguments types are not used by the type-based dispatch) -- i.e. for StenoGraph-based constructor the `graph` kw argument made positional.
  * replaced no-op constructors (e.g. `RAMMatrices(a::RAMMatrices) = a`) with `convert(RAMMatrices, a::RAMMatrices) = a` -- that's how `Base.convert()` is designed to work in Julia.
  * in `ParameterTable`: switched from `partable.variables[:observed_vars]` to `partable.observed_vars`
  * renamed `parameter_type` to `relation` in the `ParameterTable` columns (part of #199)
  * renamed `identifier` to `param` in the `ParameterTable` columns (part of #199)
  * replaced `identifier()`, `get_par_npar_identifier()` methods with `params()` call which returns a vector of SEM parameter IDs (part of #199)
  * renamed `n_par()` into `nparams()` (part of #199)
  * added `params` field to `ParameterTable` to explicitly define the order of parameters -- simplifies the logic of SEM ensembles and checking/updating parameters
  * added code for checking the correctness of parameter and variables (dimension matching, uniqueness) at the time of SEM construction
  * `param_values`/`lavaan_param_values()` -- moved the code for extracting the parameter values from the parameter tables from tests into the SEM API.

2024-05-03 15:28 UTC, alyst commented on src/additional_functions/helper.jl
> +skipmissing_mean(mat::AbstractMatrix) =
Hmm, this false positive reappears again.

2024-05-04 20:07 UTC, Maximilian-Stefan-Ernst commented on src/frontend/fit/fitmeasures/n_par.jl
> -    n_par(sem_fit::SemFit)
Maybe we want to keep this small documentation?

2024-05-04 22:40 UTC, alyst commented on src/frontend/fit/fitmeasures/n_par.jl
> -    n_par(sem_fit::SemFit)
Sure. There's a docstring for *nparams()* and *params()* in *types.jl*.

2024-05-07 12:57 UTC, Maximilian-Stefan-Ernst commented on src/frontend/fit/fitmeasures/n_par.jl
> -    n_par(sem_fit::SemFit)
Ah sry, did not see that (yet) :)

2024-05-07 13:00 UTC, Maximilian-Stefan-Ernst commented on src/frontend/specification/EnsembleParameterTable.jl
> +    params::Vector{Symbol}
I guess we could just decide that the keys should be Symbols?
```suggestion
struct EnsembleParameterTable <: AbstractParameterTable
    tables::Dict{Symbol, ParameterTable}
    params::Vector{Symbol}
```

2024-05-11 20:47 UTC, alyst commented
It looks like SymbolicsUtils 1.6 broke `sparsehessian`, so I downgraded it to 1.5.
Also, allowed StenoGraphs 0.3.

2024-05-16 08:56 UTC, Maximilian-Stefan-Ernst commented on src/frontend/specification/EnsembleParameterTable.jl
Maybe we want to have something like this:
```suggestion

EnsembleParameterTable(ps::Pair{K, V}...; params = nothing) where {K, V} = EnsembleParameterTable(Dict(ps...); params=params)

```
So users can just write
```
partable = EnsembleParameterTable(:Pasteur => specification_g1, :Grant_White => specification_g2))
```
instead of having to construct the Dict themselves every time:
```
partable = EnsembleParameterTable(
    Dict(:Pasteur => specification_g1, :Grant_White => specification_g2),
)
```

2024-05-16 09:17 UTC, Maximilian-Stefan-Ernst commented on src/frontend/specification/EnsembleParameterTable.jl
> +        update_partable!(partable, column, param_values, default)
Sorry, GitHub does not let me make a commitable suggestion by deleting the following lines too...
```suggestion
    return update_partable!(partables, column, Dict(zip(params, values)), default)
```

2024-05-16 09:54 UTC, Maximilian-Stefan-Ernst commented on src/frontend/specification/ParameterTable.jl
>          tf = PrettyTables.tf_compact,
I think its a good change to replace the unused/unitialized entried in the parameter tables with `NaN` instead of some default values, and I think it would also be nice not to print all these values, this:
```suggestion
        tf = PrettyTables.tf_compact,
        formatters = (v, i, j) -> isa(v, Number) && isnan(v) ? "" : v,
```
leads to not printing 
```
 --------- ---------- --------- ------- ------------- --------- ---------- --------
     from   relation        to    free   value_fixed     start   estimate    param 
   Symbol     Symbol    Symbol    Bool       Float64   Float64    Float64   Symbol 
 --------- ---------- --------- ------- ------------- --------- ---------- --------
   visual          →        x1   false           1.0       NaN        NaN    const
   visual          →        x2    true           NaN       NaN        NaN       λ₂
   visual          →        x3    true           NaN       NaN        NaN       λ₃
  textual          →        x4   false           1.0       NaN        NaN    const
  textual          →        x5    true           NaN       NaN        NaN       λ₅
  textual          →        x6    true           NaN       NaN        NaN       λ₆
    speed          →        x7   false           1.0       NaN        NaN    const
    speed          →        x8    true           NaN       NaN        NaN       λ₈
    speed          →        x9    true           NaN       NaN        NaN       λ₉
       x1          ↔        x1    true           NaN       NaN        NaN      θ_1
       x2          ↔        x2    true           NaN       NaN        NaN      θ_2
       x3          ↔        x3    true           NaN       NaN        NaN      θ_3
       x4          ↔        x4    true           NaN       NaN        NaN      θ_4
       x5          ↔        x5    true           NaN       NaN        NaN      θ_5
       x6          ↔        x6    true           NaN       NaN        NaN      θ_6
       x7          ↔        x7    true           NaN       NaN        NaN      θ_7
       x8          ↔        x8    true           NaN       NaN        NaN      θ_8
       x9          ↔        x9    true           NaN       NaN        NaN      θ_9
   visual          ↔    visual    true           NaN       NaN        NaN     θ_10
  textual          ↔    visual    true           NaN       NaN        NaN     θ_11
    speed          ↔    visual    true           NaN       NaN        NaN     θ_12
  textual          ↔   textual    true           NaN       NaN        NaN     θ_13
    speed          ↔   textual    true           NaN       NaN        NaN     θ_14
    speed          ↔     speed    true           NaN       NaN        NaN     θ_15
 --------- ---------- --------- ------- ------------- --------- ---------- --------
```
but instead
```
 --------- ---------- --------- ------- ------------- --------- ---------- --------
     from   relation        to    free   value_fixed     start   estimate    param 
   Symbol     Symbol    Symbol    Bool       Float64   Float64    Float64   Symbol 
 --------- ---------- --------- ------- ------------- --------- ---------- --------
   visual          →        x1   false           1.0                         const
   visual          →        x2    true                                          λ₂
   visual          →        x3    true                                          λ₃
  textual          →        x4   false           1.0                         const
  textual          →        x5    true                                          λ₅
  textual          →        x6    true                                          λ₆
    speed          →        x7   false           1.0                         const
    speed          →        x8    true                                          λ₈
    speed          →        x9    true                                          λ₉
       x1          ↔        x1    true                                         θ_1
       x2          ↔        x2    true                                         θ_2
       x3          ↔        x3    true                                         θ_3
       x4          ↔        x4    true                                         θ_4
       x5          ↔        x5    true                                         θ_5
       x6          ↔        x6    true                                         θ_6
       x7          ↔        x7    true                                         θ_7
       x8          ↔        x8    true                                         θ_8
       x9          ↔        x9    true                                         θ_9
   visual          ↔    visual    true                                        θ_10
  textual          ↔    visual    true                                        θ_11
    speed          ↔    visual    true                                        θ_12
  textual          ↔   textual    true                                        θ_13
    speed          ↔   textual    true                                        θ_14
    speed          ↔     speed    true                                        θ_15
 --------- ---------- --------- ------- ------------- --------- ---------- --------
```

2024-05-16 12:31 UTC, Maximilian-Stefan-Ernst commented on src/frontend/specification/ParameterTable.jl
> +    i > length(partable) ? nothing : (partable[i], i + 1)
You can get away with this :)
```suggestion
Base.iterate(partable::ParameterTable, i::Integer = 1) =
    i > length(partable) ? nothing : (partable[i], i + 1)
```

2024-05-16 14:35 UTC, Maximilian-Stefan-Ernst commented on src/frontend/specification/ParameterTable.jl
> +            if !(eix <= length(edges) && last(edges[eix]) == var)
I think you can use `findfirst` here to avoid the complicated checks in the if-condition
```suggestion
            eix = findfirst(e -> e[2] == var, edges)
            if isnothing(eix)
```

2024-05-16 14:35 UTC, Maximilian-Stefan-Ernst commented on src/frontend/specification/ParameterTable.jl
> +    sort!(edges, by = last) # sort edges by target
Does this provide a speed advantage?

2024-05-16 14:39 UTC, Maximilian-Stefan-Ernst commented on src/frontend/specification/ParameterTable.jl
> +before the dependent variables, and return the copy of `partable`.
```suggestion
Sort variables in `partable` so that all independent variables are
before the dependent variables, and return a copy of `partable`
where the sorted variables are in `partable.variables.sorted`.
```

2024-05-16 15:35 UTC, Maximilian-Stefan-Ernst commented on src/frontend/specification/ParameterTable.jl
> +    for (key, val) in pairs(d)
I think we should prevent people from adding partable rows that have more / less keys than columns, as this will lead to some quite weird behavior...
```suggestion
function Base.push!(partable::ParameterTable, d::Union{AbstractDict{Symbol}, NamedTuple})
    issetequal(keys(a), keys(b)) || throw(ArgumentError("The new row needs to have the same keys as the columns of the parameter table."))
    for (key, val) in pairs(d)
```

2024-05-16 19:13 UTC, Maximilian-Stefan-Ernst commented on src/frontend/specification/ParameterTable.jl
> +    resize!(coldata, length(partable))
```suggestion
    coldata = get!(() -> Vector{T}(undef, length(partable)), partable.columns, column)
```

2024-05-16 19:26 UTC, Maximilian-Stefan-Ernst commented on src/frontend/specification/ParameterTable.jl
> +Write starting values from `fit` or `start_val` to the `:estimate` column of `partable`.
```suggestion
Write starting values from `fit` or `start_val` to the `:start` column of `partable`.
```

2024-05-16 19:47 UTC, Maximilian-Stefan-Ernst commented on src/frontend/specification/ParameterTable.jl
> +            @assert out[param_ind] ≈ val atol = 1E-10 "Parameter :$param value at row #$i ($val) differs from the earlier encountered value ($(out[param_ind]))"
I'm not sure we need a tolerance for comparing these values - if the parameters are the same, their value should be exactly the same I think.

2024-05-16 19:57 UTC, Maximilian-Stefan-Ernst commented on src/frontend/specification/ParameterTable.jl
> +            @assert out[param_ind] ≈ val atol = 1E-10 "Parameter :$param value at row #$i ($val) differs from the earlier encountered value ($(out[param_ind]))"
If we wan't to keep the approximate comparison, we would have to write 
```suggestion
            @assert isapprox(out[param_ind], val, atol = 1e-10) "Parameter :$param value at row #$i ($val) differs from the earlier encountered value ($(out[param_ind]))"
```
because otherwise, it trows `AssertionError: 1.0e-10`, omitting the message.

2024-05-16 23:49 UTC, alyst commented on src/frontend/specification/EnsembleParameterTable.jl
I like your suggestion. For this (already extensive) PR I tried to limit changes to the public API.
Basically, I touched EnsParTable only for the internal cleanups and to make sure all subtypes of *SemSpecification* can provide *params* and observed/latent vars.
I suggest that we implement more user-visible changes once this PR is merged.

2024-05-16 23:58 UTC, alyst commented on src/frontend/specification/ParameterTable.jl
> +            if !(eix <= length(edges) && last(edges[eix]) == var)
The point of using `searchsortedfirst()` is to find an edge with *O(log N)* comparisons (the edges are sorted by the incoming vertex) instead of *O(N)* that you get with `findfirst()`.

2024-05-17 00:01 UTC, alyst commented on src/frontend/specification/ParameterTable.jl
> +    sort!(edges, by = last) # sort edges by target
Yes, it allows using *searchsortedfirst*

2024-05-17 06:53 UTC, Maximilian-Stefan-Ernst commented on src/frontend/specification/EnsembleParameterTable.jl
Agreed.

2024-05-17 11:21 UTC, Maximilian-Stefan-Ernst commented on src/frontend/specification/StenoGraphs.jl
> +AbstractStenoGraph = AbstractVector
How can I understand this line? ^^

2024-05-17 13:21 UTC, Maximilian-Stefan-Ernst requested changes
Finally done with the review^^ Very nice changes, the only things to do before merging are
- [ ] resolve my comments
- [ ] fix docs
- [ ] decide on `params` or `parameters`

I can have a look at what's preventing the docs from building. As we discussed in the issue, I would prefer `parameters` over `params`, and then have `parameters()` and `nparameters()` accordingly. @aaronpeikert maybe you can give a preference, and then we decide by majority^^ (Altough there are many occurences, finding and replacing all instances of `param` with `parameter` should do the trick.)

2024-05-17 14:26 UTC, aaronpeikert commented
I prefer parameters. But its more like a 60/40 preference.

2024-05-17 17:36 UTC, alyst commented on src/frontend/specification/StenoGraphs.jl
> +AbstractStenoGraph = AbstractVector
You are right, I should have probably added an explanation there:
`// FIXME: remove when StenoGraphs.jl will provide AbstractStenoGraph`

The reason is -- in this PR I switch constructors of *SemSpecification* objects from keyword arguments to positional arguments, which enables types-based dispatch (it simplifies the code a bit and makes it more type-agnostic).
It requires that input types for different ctors are unambiguously distinct (*ParameterTable*, *StenoGraph*, *RAMMatrices*).
*StenoGraphs.jl* does not provide its own graph type, but luckily the vector of edges (which is the current representation of the graph in *StenoGraphs.jl*) is unambiguous.

2024-05-17 18:09 UTC, alyst commented
@Maximilian-Stefan-Ernst Thank you for the review, I'll address your comments in a next few days.

Regarding the `params` vs `parameters`. I prefer `params`, but I can change it to `parameters` if the stakeholders decide so :)
Just to summarize my approach:
  * the core idea is to have sort-of "Huffman coding" for the terms in the API: frequently used concepts should use shorter, unambiguous, intuitive terms ("vars", "params", "cov");
    less frequently used terms, or the ones that don't have an intuitive short version, could be longer (objective, gradient, hessian); also object type names could be longer because they are less frequently used in the code.
   I think it makes the code more readable -- code lines are shorter and faster to read; the urge to introduce local variables just for the sake of avoiding using full names (e.g. `npar = nparameters(model)`) is more subdued :)
  * that is in line with Julia naming conventions (struct, Dict, Ref, Val, eval, undef, Stats, sortperm, cov), there are precedents in the other popular packages, e.g. [HTTP.getparam()](https://juliaweb.github.io/HTTP.jl/stable/reference/#HTTP.Handlers.getparam)
  * it has to be consistent with the other terms: if it's decided on `parameters`, it probably also means switching to `variables`, `covariation` etc

2024-05-19 22:21 UTC, Maximilian-Stefan-Ernst commented
Docs are fixed.

2024-05-22 19:19 UTC, Maximilian-Stefan-Ernst commented on src/frontend/specification/StenoGraphs.jl
> +AbstractStenoGraph = AbstractVector
Makes sense - I opened an issue in `StenoGraphs`. In the meantime, maybe something like this is a bit more precise:
```suggestion
#FIXME: remove when StenoGraphs.jl will provide AbstractStenoGraph
const AbstractStenoGraph = AbstractArray{T, 1} where {T <: StenoGraphs.AbstractEdge}
```

2024-05-25 11:30 UTC, Maximilian-Stefan-Ernst commented
W.r.t. the `params` vs `parameters` debate - let's settle on `params` then, I am also more like a 60/40 for `parameters`, but since you have a clear preference for `params` we can settle on it by weighted majority vote^^.

Fun fact: I tried to see what Julia `Base` is using; `params` matches 19 files, `parameters` 42 - so `Base` settled on using both^^.

2024-05-27 06:27 UTC, alyst commented on src/frontend/specification/ParameterTable.jl
> +            @assert out[param_ind] ≈ val atol = 1E-10 "Parameter :$param value at row #$i ($val) differs from the earlier encountered value ($(out[param_ind]))"
Thanks. I've changed it to the exact comparison. The initial idea was that if the estimates for the same parameter were somehow obtained independently, we may allow them to be different.
But as the current tests pass with the exact comparison I agree it is better not to complicate the logic.

2024-05-27 06:29 UTC, alyst commented
@Maximilian-Stefan-Ernst Thanks for your review and fixes! -- I've squashed them into original commits to make the history cleaner.
Special thanks for settling on `params` -- I guess I was 80/20 for it :) But if your preference for `parameters()` would grow stronger, you can always change.
Let me know if anything else is left for merging this PR.

Note regarding the doc fixes and other API tweaks (e.g. `params_indices()`) -- as there are other potential changes from #193 (and I have other ones recently) you may want to incorporate, I think it would be better to update the documentation after all of that potential updates are reviewed. I am a bit busy with my work-related projects, but I'll try to branch the next round of updates from #193 once this PR is merged.
The next things should be more material :) (ParamsArray for RAM matrix simplification, evaluate!() interface for unified objective/gradient/hessian evaluation)

2024-05-27 07:42 UTC, Maximilian-Stefan-Ernst commented
Nice, thanks again for contributing all those changes :) Before merging, there are only 2 open comments/suggestions remaining. I think we should then merge this PR and the following ones into devel - after all the changes are merged and we want to make a new release, we can then merge devel into main.

2024-05-27 08:10 UTC, alyst commented on src/frontend/specification/ParameterTable.jl
>          tf = PrettyTables.tf_compact,
I agree it would be nice not to show autofilled NaNs.
I just think the proper fix would be to allow missing values in that columns (`value_fixed`, `start`, and maybe `estimate` as well), use *missing* instead of *NaNs* for autofilling, and suppress the output of `missing`.
Otherwise there is a danger that some NaNs are not autofilled, e.g. there is some calculation bug, but it would be hidden from the user.
But as allowing missing and changing NaN to missing is a more extensive change, I suggest to move it to a separate PR.

2024-05-27 08:13 UTC, alyst commented
> Before merging, there are only 2 open comments/suggestions remaining.

Oh, right, I overlooked those. I've incorporated the iteration cleanup; as for pretty printing tweak -- see my comment.

2024-05-27 08:20 UTC, Maximilian-Stefan-Ernst commented on src/frontend/specification/ParameterTable.jl
>          tf = PrettyTables.tf_compact,
Allowing missings would be the cleanest solution. I think we can still suppress printing of `NaN`s for now, because if some calculation bug would lead to a `NaN`, I think the user is more likely to spot a blank spot where they expect a number than to spot one `NaN` too much in a sea of `NaN`s ^^.

2024-05-27 08:26 UTC, alyst commented on src/frontend/specification/ParameterTable.jl
>          tf = PrettyTables.tf_compact,
Sure, NaN suppression could be implemented as a intermediate solution.
Do you think it should be a part of this PR?
I tried to avoid changing the logic of `show()`, just some code updates to make it in-sync with the rest. Any tweaks to the logic could be implemented once it is merged.

2024-05-27 09:11 UTC, Maximilian-Stefan-Ernst commented on src/frontend/specification/ParameterTable.jl
>          tf = PrettyTables.tf_compact,
I think it can just be part of this PR - it already introduces some minor changes to the public API, so I think it's fine. I think I would merge this now into devel anyways, and make a breaking release sometimes later, when we collected more of your changes, so we don't make too many breaking releases in a short amount of time^^.

2024-05-27 09:27 UTC, alyst commented on src/frontend/specification/ParameterTable.jl
>          tf = PrettyTables.tf_compact,
Should be done now

2024-05-27 11:34 UTC, Maximilian-Stefan-Ernst approved these changes

2024-05-27 18:19 UTC, alyst commented
I've rebased the branch onto devel, the conflicts are resolved.

2024-05-27 22:31 UTC, alyst commented
@Maximilian-Stefan-Ernst  I've revised your `param_indices()` addition.
`param_indices(semobj)` is a useful one-liner method, which I actually wanted to add myself.
However, I removed `param_indices(semobj, params)` method for 2 reasons:
  * it is potentially confusing that the return type of methods with the same name is different
  * internally, `param_indices(semobj, params)` constructs the parameters dictionary at each call, which may get misused in certain contexts for large models (e.g. getting parameter indices in a loop). I think it is just a tiny bit inconvenient if instead the user has to call `param_indices(semobj)` and then use it as a dictionary, but it is a bit less likely to be misused.

2024-05-30 18:50 UTC, alyst commented
@Maximilian-Stefan-Ernst Let me know if there's anything else to tweak for this PR. Otherwise I am ready to rebase #193 once this one gets merged and extract the next round of changes :)

2024-05-31 08:03 UTC, merged

2024-05-31 08:04 UTC, Maximilian-Stefan-Ernst commented
Sorry, just too much other stuff to do :)